Fiap.Exemplo01.mvc/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo01.mvc.Models
{
    public class Aluno
    {

        public String Nome { get; set; }
        public DateTime DtNascimento { get; set; }
        public decimal Salario { get; set; }

    }
}

Fiap.Exemplo01.mvc/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fiap.Exemplo01.mvc.Models;

namespace Fiap.Exemplo01.mvc.Controllers
{
    public class AlunoController : Controller
    {
        // Action para abrir o formulário
        [HttpGet]
        public ActionResult Cadastro()
        {
            return View();
        }

        //Action para cadastrar as informações do formulário
        [HttpPost]
        public ActionResult Salvar(Aluno aluno)
        {
            ViewBag.nomeAluno = aluno.Nome;
            ViewBag.dataAluno = aluno.DtNascimento;
            ViewBag.salarioAluno = aluno.Salario;
            TempData["mensagem"] = "Cadastrado com sucesso!";
            return View(aluno);
           
        }

    }
}

Fiap.Exemplo01.mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo01.mvc.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fiap.Exemplo01.mvc/Views/Aluno/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro</h2>

<div>
    <form method="post" action="~/Aluno/Salvar">
        <div class="form-group">
            <label  for="nome">Nome:</label>
            <input type="text" name="Nome" id="id-nome" class="form-control" />
        </div>

        <div class="form-group">
            <label for="dtNascimento">Data de Nascimento</label>
            <input name="DtNascimento" type="datetime" id="id-dtNascimento" class="form-control" />
        </div>
        <div class="form-group">
            <label for="salario">Salário</label>
            <input type="number" name="Salario"  id="id-salario" class="form-control" />
        </div>
            <input type="submit" name="Salvar" class="btn btn-primary" />

</form>
</div>

Fiap.Exemplo01.mvc/Views/Aluno/Salvar.cshtml
@model Fiap.Exemplo01.mvc.Models.Aluno
@{
    ViewBag.Title = "Salvar";
}



<h2>Salvar</h2>
<h2>@TempData["mensagem"]</h2>
<h2>@Model.Nome @Model.Salario @Model.DtNascimento</h2>

<h3>O nome do aluno é @ViewBag.nomeAluno</h3>
<h3>A data de nascimento do aluno é @ViewBag.dataAluno</h3>
<h3>O Salário do aluno é @ViewBag.salarioAluno</h3>

Fiap.Exemplo01.mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Fiap.Exemplo01.mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Cadastrar Cliente", "Cadastro", "Aluno", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>